name: Deploy to Surge

on:
  push:
    branches:
      - master  # o la rama que desees

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: |
          surge --token ${{ secrets.SURGE_TOKEN }} ./ --domain <your-custom-domain>.surge.sh
